#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// Returns 1 if strings are identical, 0 otherwise
int isMatch(char a[], char *b) {
    int i = 0;
    while (a[i] != '\0' && b[i] != '\0') {
        if (a[i] != b[i]) {
            return 0; // Mismatch found
        }
        i++;
    }
    // Only equal if BOTH reached the end ('\0') together
    if (a[i] == '\0' && b[i] == '\0') {
        return 1;
    }
    return 0;
}

void match(char a[], char *b) {
    // 1. Tie Check
    if (isMatch(a, b)) {
        printf("It's a Tie.\n");
        return;
    }

    // 2. Win Conditions
    if (isMatch(a, "paper") && isMatch(b, "stone")) {
        printf("You Won...!!\n");
    } 
    else if (isMatch(a, "scissors") && isMatch(b, "paper")) {
        printf("You Won...!!\n");
    } 
    else if (isMatch(a, "stone") && isMatch(b, "scissors")) {
        printf("You Won...!!\n");
    } 
    // 3. Otherwise, Lose
    else {
        printf("You lose.\n");
    }
}

int main() {
    char st[20];
    int y;
    char *z;

    printf("\n--- Welcome ---\n\n");
    printf("Enter stone, paper or scissors: ");
    scanf("%19s", st);
    printf("Your response: %s\n", st);

    srand(time(0));
    y = (rand() % 3) + 1;

    if (y == 1) {
        z = "stone";
    } else if (y == 2) {
        z = "paper";
    } else if (y == 3) {
        z = "scissors";
    }

    printf("Computer chose: %s\n", z);

    match(st, z);

    return 0;
}

// Generated by Gemini wrt to my method.