#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// 1. Function using switch-case that returns a string pointer
char *getMoveName(int choice) {
    switch (choice) {
        case 1:
            return "Stone";
        case 2:
            return "Paper";
        case 3:
            return "Scissors";
        default:
            return "Invalid";
    }
}

// 2. Function using Call-by-Reference to update player and computer scores
void checkWinner(int user, int comp, int *userScore, int *compScore) {
    if (user == comp) {
        printf("Result: It's a Tie!\n");
    } 
    // Win conditions: Stone(1) beats Scissors(3), Paper(2) beats Stone(1), Scissors(3) beats Paper(2)
    else if ((user == 1 && comp == 3) || 
             (user == 2 && comp == 1) || 
             (user == 3 && comp == 2)) {
        printf("Result: You Won!\n");
        (*userScore)++; // Modifying the caller's variable via pointer
    } 
    else {
        printf("Result: Computer Won!\n");
        (*compScore)++;
    }
}

int main() {
    int userChoice;
    int compChoice;
    int userScore = 0;
    int compScore = 0;
    char playAgain = 'y';

    // Seed the random number generator once at program start
    srand(time(0));

    printf("=================================\n");
    printf("     STONE - PAPER - SCISSORS    \n");
    printf("=================================\n");

    // Loop to keep playing multiple rounds
    while (playAgain == 'y' || playAgain == 'Y') {
        printf("\nChoose your move:\n");
        printf("1. Stone\n");
        printf("2. Paper\n");
        printf("3. Scissors\n");
        printf("Enter choice (1-3): ");
        scanf("%d", &userChoice);

        // Input validation using if-else
        if (userChoice < 1 || userChoice > 3) {
            printf("Invalid selection! Please enter 1, 2, or 3.\n");
            continue;
        }

        // Generate computer's choice: 1, 2, or 3
        compChoice = (rand() % 3) + 1;

        // Display move names via pointer return
        printf("\nYou chose: %s\n", getMoveName(userChoice));
        printf("Computer chose: %s\n", getMoveName(compChoice));

        // Pass scores using call-by-reference
        checkWinner(userChoice, compChoice, &userScore, &compScore);

        printf("Current Score -> You: %d | Computer: %d\n\n", userScore, compScore);

        printf("Play another round? (y/n): ");
        // Leading space inside " %c" ignores trailing newlines left in buffer
        scanf(" %c", &playAgain); 
    }

    printf("\nFinal Score -> You: %d | Computer: %d\n", userScore, compScore);
    printf("Game Over.\n");

    return 0;
}
// Fully Generated by Gemini.   zxcvbnm,  